### ISSUE TITLE
Deprecated device_registry.devices Issue

### ISSUE THREAD

**Issue by Patbonamy** [rodpayne/home-assistant_person_location#47]
I have this error:
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:348
Première occurrence: 8 septembre 2026 à 22:49:18 (1 occurrence)
Dernier enregistrement: 8 septembre 2026 à 22:49:18

Detected that custom integration 'person_location' uses `device_registry.devices` as a mapping or calls its lookup methods, which is deprecated; iterate it to get the device entries, or use `async_get`, `async_entries_for_config_entry` and similar helpers for lookups at custom_components/person_location/__init__.py, line 770: for device in list(dev_reg.devices.values()):. This will stop working in Home Assistant 2027.9.0, please create a bug report at https://github.com/rodpayne/home-assistant_person_location/issues

**Comment by rodpayne** [comment]
I added pre-release Version 2026.09.14 that includes this fix, on top of about a month's worth of other changes. If you could do some testing for me when you get a chance, that would be great.

**Comment by Patbonamy** [comment]
Hi, 
I test the 2026-09-14 pre release and all my entities are unavailable. 
Thanks for the work

**Comment by rodpayne** [comment]
Were there any warning or error messages? Did you by any chance get a diagnostic download? If you are willing to try it again, please wait a couple of minutes before doing the download so that it has time to do the startup processes.

**Comment by Patbonamy** [comment]
I try one more time I have this error:
Cette erreur provient d'une intégration personnalisée.

Logger: custom_components.person_location.services.reverse_geocode
Source: custom_components/person_location/services/reverse_geocode.py:1026
Intégration: Person Location (Documentation, Problèmes)
Première occurrence: 08:44:41 (4 occurrences)
Dernier enregistrement: 09:10:24

(sensor.cat_location) Exception TypeError: async_setup_reverse_geocode.<locals>.async_call_open_street_map_reverse_geocoding() missing 1 required positional argument: 'ctx'
(sensor.pat_location) Exception TypeError: async_setup_reverse_geocode.<locals>.async_call_open_street_map_reverse_geocoding() missing 1 required positional argument: 'ctx'

And entities are unavailable , revert to old release all is ok

**Comment by rodpayne** [comment]
Thanks for the error message! I see the problem clearly now and I have added Open Street Map to my testing.

**Comment by rodpayne** [comment]
Pre-release Version 2026.09.16 has this fix and is ready for testing.

**Comment by Patbonamy** [comment]
Thanks Rod, 
Now I have my entities OK. 
I continue testing and report you if any errors. 
Have a great day

**Comment by rodpayne** [comment]
Let me know either way. If there are no problems, I will set it as the "Latest" release for everyone.

**Comment by Patbonamy** [comment]
It's seems there's no problems.
